! ======================================================================
! PROGRAM MOMENTUMCOLLECT
! ----------------------------------------------------------------------
      PROGRAM MOMENTUMCOLLECT
      IMPLICIT NONE

      REAL, PARAMETER :: PI = 3.1415926535897932384626433832795028841971E0

      INTEGER :: NUMBER_OF_GRID_POINTS
      INTEGER :: NUMBER_OF_TIME_STEPS
      INTEGER :: NUMBER_OF_TIME_STEPS_BEFORE_WRITE
      INTEGER :: START_FILE
      INTEGER :: END_FILE
      INTEGER :: OUTPUT_FILE
      INTEGER :: START_MOMENTUM
      INTEGER :: END_MOMENTUM

      REAL :: RADIUS
      REAL :: GAMMA_FACTOR

      CHARACTER(80) :: BUFFER

      INTEGER :: CURRENT_FILE
      INTEGER :: CURRENT_GRID_POINT
      INTEGER :: CURRENT_MOMENTUM
      INTEGER :: MOMENTUM
      INTEGER :: LENGTH
      INTEGER :: INFO

      REAL :: ANGULAR_GRID_SPACING_SIZE
      REAL :: TIME_STEP_SIZE
      REAL :: TIME
      REAL :: ABSFC
      REAL :: REALFC
      REAL :: IMAGFC

      CALL GET_COMMAND_ARGUMENT(1,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) NUMBER_OF_GRID_POINTS

      CALL GET_COMMAND_ARGUMENT(2,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) NUMBER_OF_TIME_STEPS

      CALL GET_COMMAND_ARGUMENT(3,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) NUMBER_OF_TIME_STEPS_BEFORE_WRITE

      CALL GET_COMMAND_ARGUMENT(4,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) START_FILE

      CALL GET_COMMAND_ARGUMENT(5,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) END_FILE

      CALL GET_COMMAND_ARGUMENT(6,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) OUTPUT_FILE

      CALL GET_COMMAND_ARGUMENT(7,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) START_MOMENTUM

      CALL GET_COMMAND_ARGUMENT(8,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) END_MOMENTUM

      CALL GET_COMMAND_ARGUMENT(9,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) RADIUS

      CALL GET_COMMAND_ARGUMENT(10,BUFFER,LENGTH,INFO)
      READ(BUFFER,*) GAMMA_FACTOR

      ANGULAR_GRID_SPACING_SIZE = 2.0E0*PI/FLOAT(NUMBER_OF_GRID_POINTS)
      TIME_STEP_SIZE = (RADIUS*ANGULAR_GRID_SPACING_SIZE)**2/(2.0E0*GAMMA_FACTOR)
      OPEN(UNIT=OUTPUT_FILE,ACTION='WRITE',FORM='FORMATTED',STATUS='NEW')
      DO CURRENT_FILE = START_FILE, END_FILE
         TIME = FLOAT(CURRENT_FILE-START_FILE)*FLOAT(NUMBER_OF_TIME_STEPS_BEFORE_WRITE)*TIME_STEP_SIZE
         OPEN(UNIT=CURRENT_FILE,ACTION='READ',FORM='FORMATTED',STATUS='OLD')
         DO CURRENT_MOMENTUM = START_MOMENTUM, END_MOMENTUM
            READ(CURRENT_FILE,*) MOMENTUM, ABSFC, REALFC, IMAGFC
            WRITE(OUTPUT_FILE,*) TIME, MOMENTUM, ABSFC
         ENDDO
         CLOSE(UNIT=CURRENT_FILE,STATUS='KEEP')
         WRITE(OUTPUT_FILE,*) ' '
      ENDDO
      CLOSE(UNIT=OUTPUT_FILE,STATUS='SAVE')

      STOP
      ENDPROGRAM MOMENTUMCOLLECT
! =========================================================================

